cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.type: single-node
# 永久修改磁碟空間 watermark
# cluster.routing.allocation.disk.watermark.low: "90%"
# cluster.routing.allocation.disk.watermark.high: "95%"
# cluster.routing.allocation.disk.watermark.flood_stage: "98%"
# cluster.info.update.interval: "1m"
