services:
  backend:
    container_name: garmin-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - SleepGenius-network

networks:
  SleepGenius-network:
    external: true   
