services:
  frontend:
    container_name: garmin-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - SleepGenius-network

networks:
  SleepGenius-network:
    external: true   